trigger:
- main

pr:
- main

jobs:
- job: Ubuntu_Emscripten
  timeoutInMinutes: 30
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
  - script: |
      sudo apt-get update
      sudo apt-get install libgl1-mesa-dev clang-8 libc++-8-dev libc++abi-8-dev ninja-build
      git clone https://github.com/emscripten-core/emsdk.git
      ./emsdk/emsdk install latest
    displayName: 'Install packages'
  - script: |
      ./emsdk/emsdk activate latest
      source ./emsdk/emsdk_env.sh
      mkdir build
      cd build
      emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
      ninja
    displayName: 'Build Emscripten'
