// generated by CMake
#include <stdint.h>
#include <bgfx/embedded_shader.h>
#include "Node_vs_dx11.h"
#include "Node_vs_dx9.h"
#include "Node_vs_glsl.h"
#include "Node_vs_mtl.h"
#include "Node_vs_spv.h"
